CoffeyCafe/Controllers/AdminDetailsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CoffeyCafe.Models;
using System.Data.SqlClient;


namespace CoffeyCafe.Controllers
{
    public class AdminDetailsController : Controller
    {
        // GET: AdminDetails
        public ActionResult AdminLogin()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AdminLoginCheck(AdminDetails instance_Admin) {


            SqlConnection sqlcon = new SqlConnection();
            SqlCommand sqlcmd = new SqlCommand();
            SqlDataReader sqldr;

            sqlcon.ConnectionString = "Data Source=LAPTOP-RFTA97Q7\\SQLEXPRESS01;Initial Catalog=coffeCafe;Integrated Security=True";
            sqlcon.Open();
            sqlcmd.Connection = sqlcon;
            sqlcmd.CommandText = "select * from AdminDetails where AdminName='" + instance_Admin.AdminName + "' and AdminPassword='" + instance_Admin.AdminPassword + "'";

            sqldr = sqlcmd.ExecuteReader();

            if (sqldr.Read())
            {
                sqlcon.Close();
                return View("AdminDashBoard");
            }
            else
            {
                sqlcon.Close();
                return View("Wrong");
            }



        }

    }
}

CoffeyCafe/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>

        <script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
    <!--mobile apps-->
    <!--Custom Theme files -->
    <link href="~/css/bootstrap.css" type="text/css" rel="stylesheet" media="all">
    <link href="~/css/style.css" type="text/css" rel="stylesheet" media="all">
    <link href="~/css/popuo-box.css" rel="stylesheet" type="text/css" media="all" />
    <!-- //Custom Theme files -->
    <!-- js -->
    <script src="~/js/jquery-1.11.1.min.js"></script>
    <!-- //js -->
    <!--web-fonts-->
    <link href='//fonts.googleapis.com/css?family=Aladin' rel='stylesheet' type='text/css'>
    <link href='//fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic,600,600italic,700,700italic,800,800italic' rel='stylesheet' type='text/css'>
    <!--//web-fonts-->
    <!--animate-->
    <link href="~/css/animate.css" rel="stylesheet" type="text/css" media="all">
    <script src="~/js/wow.min.js"></script>
    <script>
		 new WOW().init();
    </script>
    <!--//end-animate-->
    <!-- start-smoth-scrolling-->
    <script type="text/javascript" src="~/js/move-top.js"></script>
    <script type="text/javascript" src="~/js/easing.js"></script>
    <script type="text/javascript">
		jQuery(document).ready(function($) {
			$(".scroll").click(function(event){
				event.preventDefault();
				$('html,body').animate({scrollTop:$(this.hash).offset().top},1000);
			});
		});
    </script>
    <!--//end-smoth-scrolling-->




</head>
<body>

    <!--banner-->
    <div class="banner">
        <div class="bnr-img">
            <img class="wow fadeInLeftBig animated" data-wow-delay=".5s" src="~/images/a.png" alt="" />
        </div>
        <div class="top-nav">
            <span class="menu"><img src="~/images/menu-icon.png" alt="" /></span>
            <ul class="nav1 menu-list">
                <li> <a href='@Url.Action("AdminLogin","AdminDetails")'>Coffe Cafe </a></li>


                <li class="menu-item">@Html.ActionLink("Home", "Index", "Home")</li>
                <li class="menu-item">@Html.ActionLink("About", "About", "Home")</li>
                <li class="menu-item">@Html.ActionLink("Gallery", "Gallery", "Home")</li>

                <li class="menu-item">@Html.ActionLink("Contact", "Contact", "Home")</li>
            </ul>
            <div class="clearfix"> </div>
            <!-- script-for-menu -->
            <script>
                $("span.menu").click(function () {
                    $("ul.nav1").slideToggle(300, function () {
                        // Animation complete.
                    });
                });
            </script>
            <!-- /script-for-menu -->
        </div>
        <div class="social-icons wow zoomIn animated" data-wow-delay=".5s">
            <ul>
                <li><a href="#"> </a></li>
                <li><a href="#" class="fb"> </a></li>
                <li><a href="#" class="in"> </a></li>
                <li><a href="#" class="dott"> </a></li>
            </ul>
        </div>
        <div class="banner-text">
            <h1 class="wow fadeInDown animated" data-wow-delay=".5s"><a href="#">Espresso </a> </h1>
           
            <div class="pop-up">
               
                <div id="small-dialog" class="mfp-hide book-form">
                    <form>
                        <label>Date :</label>
                        <input type="date">
                        <div class="form-left">
                            <label>City :</label>
                            <input type="text" value="City" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'City';}" required="">
                        </div>
                        <div class="form-right">
                            <label>Time :</label>
                            <input type="time">
                        </div>
                        <div class="clearfix"> </div>
                        <label>Contact Info :</label>
                        <input type="text" value="Contact Info" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Contact';}" required="">
                        <input type="submit" value="Order Now">
                    </form>
                </div>
                <!-- pop-up-box -->
                <script src="~/js/jquery.magnific-popup.js" type="text/javascript"></script>
                <!--//pop-up-box -->
                <script>
                    $(document).ready(function () {
                        $('.popup-with-zoom-anim').magnificPopup({
                            type: 'inline',
                            fixedContentPos: false,
                            fixedBgPos: true,
                            overflowY: 'auto',
                            closeBtnInside: true,
                            preloader: false,
                            midClick: true,
                            removalDelay: 300,
                            mainClass: 'my-mfp-zoom-in'
                        });
                    });
                </script>
            </div>
            <img class="wow zoomIn animated" data-wow-delay=".5s" src="images/img1.png" alt="" />
        </div>
        <div class="clearfix"> </div>
    </div>
    <!--//banner-->








    <div class="container-fluid body-content">
        @RenderBody()
        <hr />

    </div>



    <!--//popular-->
    <!--table-book-->
    <div class="table-book">
        <div class="container">
            <div class="book-info wow fadeInDown animated" data-wow-delay=".5s">
                <div class="book-left">
                    <h2 class="wow fadeInLeftBig animated" data-wow-delay=".5s">Book Your Coffee Now </h2>
                    <p class="wow fadeInLeftBig animated" data-wow-delay=".5s">Call NOW to our toll free number </p>
                </div>
                <div class="book-right">
                    <h3 class="wow fadeInRightBig animated" data-wow-delay=".5s">+64 1245 7896 </h3>
                </div>
                <div class="clearfix"> </div>
            </div>
            <span class="bg-text bg-right">B</span>
        </div>
    </div>
    <!--//table-book-->
    <!--footer-->
    <div class="footer">
        <div class="container">
            <div class="col-md-4 footer-left wow fadeInDown animated" data-wow-delay=".5s">
                <h4>Information</h4>
                <ul>
                    <li><a href='@Url.Action("Testimonial","Home")'><i class="glyphicon glyphicon-chevron-right"></i>  Testimonials</a></li>
                    <li><a href='@Url.Action("Team","Home")'><i class="glyphicon glyphicon-chevron-right"></i> Our Team</a></li>
                    <li><a href='@Url.Action("History","Home")'><i class="glyphicon glyphicon-chevron-right"></i> History</a></li>
                    <li><a href='@Url.Action("Faq","Home")'><i class="glyphicon glyphicon-chevron-right"></i> FAQ</a></li>
                </ul>
            </div>
            <div class="col-md-4 footer-left wow fadeInDown animated" data-wow-delay=".5s">
                <h4>Details</h4>
                <ul>
                    <li><a href='@Url.Action("About","Home")'><i class="glyphicon glyphicon-chevron-right"></i> About</a></li>
                    <li><a href='@Url.Action("Gallery","Home")'><i class="glyphicon glyphicon-chevron-right"></i> Gallery</a></li>
                    
                    <li><a href='@Url.Action("Contact","Home")'><i class="glyphicon glyphicon-chevron-right"></i> Contacts</a></li>

                </ul>
            </div>
            <div class="col-md-4 footer-right wow fadeInDown animated" data-wow-delay=".5s">
                <h4>Newsletter</h4>
                <div class="subscribe">
                   
                    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d408598.8546541236!2d174.5852784679175!3d-36.862144773394114!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x6d0d47fb5a9ce6fb%3A0x500ef6143a29917!2sAuckland%2C%20New%20Zealand!5e0!3m2!1sen!2sin!4v1576286658644!5m2!1sen!2sin"></iframe>
                    <div class="clearfix"> </div>
                </div>
                <div class="social-icons">
                    <ul>
                        <li><a href="#"> </a></li>
                        <li><a href="#" class="fb"> </a></li>
                        <li><a href="#" class="in"> </a></li>
                        <li><a href="#" class="dott"> </a></li>
                    </ul>
                </div>
            </div>
            <div class="clearfix"> </div>
            <div class="footer-copy wow fadeInUp animated" data-wow-delay=".5s">
                <p>© 2019 Espresso. All rights reserved | Design by </p>
            </div>
        </div>
    </div>
    <!--//footer-->
    <!--smooth-scrolling-of-move-up-->
    <script type="text/javascript">
        $(document).ready(function () {
            /*
            var defaults = {
                containerID: 'toTop', // fading element id
                containerHoverID: 'toTopHover', // fading element hover id
                scrollSpeed: 1200,
                easingType: 'linear'
            };
            */

            $().UItoTop({ easingType: 'easeOutQuart' });

        });
    </script>
    <a href="#" id="toTop" style="display: block;"> <span id="toTopHover" style="opacity: 1;"> </span></a>
    <!--//smooth-scrolling-of-move-up-->
    <!--scrolling js-->
    <script src="~/js/jquery.nicescroll.js"></script>
    <script src="~/js/scripts.js"></script>
    <!--//scrolling js-->
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="~/js/bootstrap.js"></script>
</body>
</html>