CoffeyCafe/Models/AdminDetails.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CoffeyCafe.Models
{
    public class AdminDetails
    {
        public String AdminName { get; set; }
        public String AdminPassword { get; set; }
    }
}

CoffeyCafe/Controllers/AdminDetailsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CoffeyCafe.Models;
using System.Data.SqlClient;


namespace CoffeyCafe.Controllers
{
    public class AdminDetailsController : Controller
    {
        // GET: AdminDetails
        public ActionResult AdminLogin()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AdminLoginCheck(AdminDetails instance_Admin) {


            SqlConnection sqlcon = new SqlConnection();
            SqlCommand sqlcmd = new SqlCommand();
            SqlDataReader sqldr;

            sqlcon.ConnectionString = "Data Source=LAPTOP-RFTA97Q7\\SQLEXPRESS01;Initial Catalog=coffeCafe;Integrated Security=True";
            sqlcon.Open();
            sqlcmd.Connection = sqlcon;
            sqlcmd.CommandText = "select * from AdminDetails where AdminName='" + instance_Admin.AdminName + "' and AdminPassword='" + instance_Admin.AdminPassword + "'";

            sqldr = sqlcmd.ExecuteReader();

            if (sqldr.Read())
            {
                sqlcon.Close();
                return View("AdminDashBoard");
            }
            else
            {
                sqlcon.Close();
                return View("Wrong");
            }



        }

    }
}

CoffeyCafe/Controllers/EmployeeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CoffeyCafe.Models;
namespace CoffeyCafe.Controllers
{
    public class EmployeeController : Controller
    {
        // GET: Employee
        coffeCafeEntities1 obj = new coffeCafeEntities1();

        public ActionResult ViewEmployee()
        {
            return View(obj.Employees.ToList());
        }

        // GET: Employee/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Employee/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Employee/Create
        [HttpPost]
        public ActionResult Create([Bind(Exclude = "Id")] Employee EmployeetoAdd)
        {
            if (!ModelState.IsValid)
                return View();
            obj.Employees.Add(EmployeetoAdd);
            obj.SaveChanges();

            return RedirectToAction("ViewEmployee");
            
        }

        // GET: Employee/Edit/5
        public ActionResult Edit(int ID)
        {
            var EmployeeToEdit = (from m in obj.Employees where m.id == ID select m).First();
            return View(EmployeeToEdit);
        }

        // POST: Employee/Edit/5
        [HttpPost]
        public ActionResult Edit(Employee EmployeeToEdit)
        {

            var orignalRecord = (from m in obj.Employees where m.id == EmployeeToEdit.id select m).First();

            if (!ModelState.IsValid)
                return View(orignalRecord);
            obj.Entry(orignalRecord).CurrentValues.SetValues(EmployeeToEdit);

            obj.SaveChanges();
            return RedirectToAction("ViewEmployee");
        }

        // GET: Employee/Delete/5
        public ActionResult Delete(Employee EmployeeToDelete)
        {
            var d = obj.Employees.Where(x => x.id ==EmployeeToDelete.id).FirstOrDefault();
            obj.Employees.Remove(d);
            obj.SaveChanges();
            return RedirectToAction("ViewEmployee");
        }

        // POST: Employee/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

CoffeyCafe/Controllers/SalaryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CoffeyCafe.Models;
namespace CoffeyCafe.Controllers
{
    public class SalaryController : Controller
    {
        // GET: Salary
        coffeCafeEntities1 obj = new coffeCafeEntities1();
        public ActionResult ViewPaymentDetails()
        {
            return View(obj.Salaries.ToList());
        }

        // GET: Salary/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Salary/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Salary/Create
        [HttpPost]
        public ActionResult Create([Bind(Exclude = "Id")] Salary EmployeePayment)
        {
            if (!ModelState.IsValid)
                return View();
            obj.Salaries.Add(EmployeePayment);
            obj.SaveChanges();

            return RedirectToAction("ViewPaymentDetails");
        }

        // GET: Salary/Edit/5
        public ActionResult Edit(int id)
        {
            var SalaryToEdit = (from m in obj.Salaries where m.id == id select m).First();
            return View(SalaryToEdit);
        }

        // POST: Salary/Edit/5
        [HttpPost]
        public ActionResult Edit(Salary SalaryToEdit)
        {
            var orignalRecord = (from m in obj.Salaries where m.id == SalaryToEdit.id select m).First();

            if (!ModelState.IsValid)
                return View(orignalRecord);
            obj.Entry(orignalRecord).CurrentValues.SetValues(SalaryToEdit);

            obj.SaveChanges();
            return RedirectToAction("ViewPaymentDetails");
        }

        // GET: Salary/Delete/5
        public ActionResult Delete(Salary SalaryToDelete)
        {
            var d = obj.Salaries.Where(x => x.id == SalaryToDelete.id).FirstOrDefault();
            obj.Salaries.Remove(d);
            obj.SaveChanges();

            return RedirectToAction("ViewPaymentDetails");
        }

        // POST: Salary/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

CoffeyCafe/Views/AdminDetails/AdminDashBoard.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}


    <div class="container">
        <h1>Wel Come to the Dashboard </h1>






        <a href='@Url.Action("ViewEmployee","Employee")' class="col-md-12 btn btn-warning">Employee Area </a>

        <a href='@Url.Action("ViewPaymentDetails","Salary")' class="col-md-12 btn btn-warning">Salary Area </a>


        <a href='@Url.Action("Index","Home")'>Back to Main Site </a>

    </div>

CoffeyCafe/Views/AdminDetails/AdminLogin.cshtml
@{
    ViewBag.Title = "AdminLogin";
}


<!-- contact -->
<div class="contact">
    <div class="container">
        <h4 class="title wow fadeInDown animated" data-wow-delay=".5s">Admin Login </h4>
         <div class="contact-form">
            
            <div class="col-md-7 contact-right wow fadeInRight animated" data-wow-delay=".5s">
                
                
                <form method="post" action="AdminLoginCheck">
                    
                    <input class="email" name="AdminName" id="AdminName" type="text" placeholder="Email" required="">
                    <input type="text" name="AdminPassword" id="AdminPassword" placeholder="Password" required="">
                    <br/>
                    <input class="wow zoomIn animated" data-wow-delay=".5s" type="submit" value="SUBMIT">
                    <input class="wow zoomIn animated" data-wow-delay=".5s" type="reset" value="CLEAR">
                </form>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>
</div>
<!-- //contact -->

CoffeyCafe/Views/AdminDetails/Wrong.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<div class="container">
    <h1>Please Type the Correct Id and Password </h1>








    <a href='@Url.Action("Index","Home")'>Back to Main Site </a>

</div>